// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Refresh",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/databases": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Database"
                ],
                "summary": "Get databases",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.GetDatabasesResponseItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/databases/{database_id}/datatypes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Datatype"
                ],
                "summary": "Get datatypes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagram"
                ],
                "summary": "Get requesters diagrams",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagram"
                ],
                "summary": "Create diagram",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams/access/{access_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessRight"
                ],
                "summary": "Delete access rights",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Access ID",
                        "name": "access_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams/tables/relations": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relation"
                ],
                "summary": "Create relation",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams/tables/relations/{relation_id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relation"
                ],
                "summary": "Edit relation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Relation ID",
                        "name": "relation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relation"
                ],
                "summary": "Delete relation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Relation ID",
                        "name": "relation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/diagrams/tables/rows/{row_id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Row"
                ],
                "summary": "Edit row",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Row ID",
                        "name": "row_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Row"
                ],
                "summary": "Delete row",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Row ID",
                        "name": "row_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/diagrams/tables/{table_id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Edit table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Delete table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/diagrams/tables/{table_id}/rows": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Row"
                ],
                "summary": "Create row",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams/{diagram_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagram"
                ],
                "summary": "Get diagram",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagram"
                ],
                "summary": "Edit diagram",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagram"
                ],
                "summary": "Delete diagram",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/diagrams/{diagram_id}/access": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessRight"
                ],
                "summary": "Get access rights",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessRight"
                ],
                "summary": "Give access rights",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/diagrams/{diagram_id}/tables": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Create table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Diagram ID",
                        "name": "diagram_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        },
        "/v1/tables/{table_id}/coordinates": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coordinate"
                ],
                "summary": "Get table coordinates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coordinate"
                ],
                "summary": "Get table coordinates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/users/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get requester user",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Edit requester user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en-US",
                        "description": "Language preference",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.NotImplemented"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.GetDatabasesResponseItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.NotImplemented": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Free-Diagrams SQL API",
	Description:      "Free-Diagrams SQL API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
